---
blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/grzegorzfranus/ansible-role-node-exporter/discussions
    about: Please ask questions and discuss ideas there.
